# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pr:
  branches:
    include:
    - '*' 

stages:
- stage: Build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - script: echo Build
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm install -g @aws-amplify/cli
        amplify pull --appId d3rn4p2tzz99aw --envName local
        npm run build
      displayName: 'npm install,amplify/cli and build'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ./build
        artifactName: build
      
- stage: Test
  dependsOn: Build
  jobs:
  - job: run_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - script: echo Testing... nothing to test..
    
- stage: Staging
  dependsOn: Test
  jobs:
  - job: deploy_staging
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - script: echo Staging
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: build
          
    - task: S3Upload@1
      inputs:
        awsCredentials: 'aws-s3-connection'
        regionName: 'ap-south-1'
        bucketName: 'pashes3'
        sourceFolder: './build'
        globExpressions: '**'
