/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a08097ef-8f2b-47ee-81ef-e27ed36296b3",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_6cDIfDfoc",
    "aws_user_pools_web_client_id": "1p305v2dndvlll4m2jp9aq5721",
    "oauth": {}
};


export default awsmobile;
